### ISSUE TITLE
How to use with niv (without <nixpkgs>)?

### ISSUE THREAD

**Issue by bbigras** [Mic92/nix-build-uncached#10]
Any idea how to use "nix run" with niv?

I'm currently using the following but it would be nice to be able to use it with `"skip_adding_nixpkgs_channel": true`:

https://github.com/bbigras/nix-config/blob/91239cc64a25cc695e395d96d7947894c2ed0327/.github/workflows/ci.yml#L35-L38

**Comment by Mic92** [comment]
~You can use nix builtin fetcher: `niv update -a builtin=true nixpkgs`~

```
$ nix run '((import (import ./sources.nix).nixpkgs {}).nix-build-uncached)' -c nix-build-uncached
```

**Comment by Mic92** [comment]
You can even make it more efficient by only uploading locally build packages: https://github.com/Mic92/dotfiles/blob/master/.github/workflows/build.yml#L55

**Comment by bbigras** [comment]
> $ nix run '((import (import ./sources.nix).nixpkgs {}).nix-build-uncached)' -c nix-build-uncached

Thanks. It works :smile: 

> ~~You can use nix builtin fetcher: niv update -a builtin=true nixpkgs~~

I'm curious. What does `builtin` do with `niv`?

> You can even make it more efficient by only uploading locally build packages: https://github.com/Mic92/dotfiles/blob/master/.github/workflows/build.yml#L55

Sweet. Thank you very much!

**Comment by bbigras** [comment]
Is `nix shell` only available with flakes?

**Comment by Mic92** [comment]
> Is `nix shell` only available with flakes?

Yes. I documented all new commands here: https://nixos.wiki/wiki/Nix_command

**Comment by bbigras** [comment]
Thanks! :smile:
