### ISSUE TITLE
Flakes docs don't work

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-build-uncached#11]
AFAICT the flakes docs don't work.

`getFlake` is only available when flakes is enabled, I don't think it works from nix-build, or at least I can't get it to.

I assume flake-compat will work? I'm going to try.

**Comment by colemickens** [comment]
This does what I need:

`packages.nix`
```nix
let
  flake = (import (fetchTarball {
    url="https://github.com/edolstra/flake-compat/archive/c75e76f80c57784a6734356315b306140646ee84.tar.gz";
    sha256="071aal00zp2m9knnhddgr2wqzlx6i6qa1263lv1y7bdn2w20h10h";
  }) {
    src = builtins.fetchGit ./.;
  }).defaultNix;
in
  builtins.attrValues
    flake.packages."${builtins.currentSystem}"
```

**Comment by Mic92** [comment]
> AFAICT the flakes docs don't work.
> 
> `getFlake` is only available when flakes is enabled, I don't think it works from nix-build, or at least I can't get it to.
> 
> I assume flake-compat will work? I'm going to try.

Yes. It assumes that your nix has flakes enabled. But than `nix-build` should also work.

**Comment by colemickens** [comment]
Weird, yeah, it works now and isn't complaining about `getFlake` working. (I really did enable flakes system-wide last night).

Well, anyway, I need this to work in CI where I don't think I have control over the daemon or don't want to mess with it, so I'll probably keep using this (being my flake-compat version) anyhow.

That having been said, this issue isn't valid afaict.

**Comment by Mic92** [comment]
There is a way to get flake-enabled nix version in CI: https://github.com/nix-community/nix-direnv/blob/master/.github/workflows/test.yml
