### ISSUE TITLE
Output can't be piped to cachix

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-build-uncached#12]
It looks like this prints stuff to stdout instead of stderr maybe.

It's nice to be able to just pipe everything to cachix, especially when still using `nix-build` and it might output numerous out-links, or results to stdout.

Is it just a matter of changing the `fmt.Println`s in `build.go` to print to stderr instead?

**Comment by colemickens** [comment]
I think I'll do something like this in the meantime. There's probably an easier way I'm just not thinking of.

```
out="$(mktemp -d)"
nix-build-uncached \
  --option "extra-binary-caches" "https://cache.nixos.org https://nixpkgs-wayland.cachix.org" \
  --option "trusted-public-keys" "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA=" \
  --option "build-cores" "0" \
  --option "narinfo-cache-negative-ttl" "0" \
  --out-link "${out}/result" packages.nix

results=(); shopt -s nullglob
for f in ${out}/result*; do
  results=("${results[@]}" "${f}")
done
echo "${results[@]}" | cachix push "${cache}"
```

**Comment by Mic92** [comment]
I can take a look into that. Right now on github I use `nix path-info --all` https://github.com/cachix/cachix-action/blob/master/src/main.ts#L44

It also has the benefit that it can skip downloaded derivations: https://github.com/Mic92/dotfiles/blob/master/.drone.yml#L54

If you have a stateful ci, the you probably prefer result symlinks anyway because it prevents garbage collection of some build artifacts.

**Comment by Mic92** [comment]
Right now it is using `nix build` to perform the actual build, which does not print store paths on stdout.

**Comment by colemickens** [comment]
I actually don't like this bug report, the hyphenated `nix-build-uncached` throws me off, but it does even remind me at the end that it runs `nix build`.

Since `nix build` doesn't output paths to stdout, I'm not sure it makes sense to expect it from a build wrapper. Seems like there are a few ways to go about this anyway.

I'm going to close this.
