### ISSUE TITLE
`allowSubstitutes = false` issue

### ISSUE THREAD

**Issue by zimbatm** [Mic92/nix-build-uncached#13]
Derivations with `allowSubstitutes = false` like all the trivial builders are getting marked for rebuild every time.

**Comment by zimbatm** [comment]
I figure this out. Wrap all the derivations so none of the leafs have `allowSubstitutes = false`. This version works but should also be augmented to recurse into the attributes:
```nix
{ system ? builtins.currentSystem }:
let
  pkgs = import ./. { inherit system; };

  # Derivations with `allowSubstitutes = false` always get marked for rebuild.
  # So we wrap them.
  toCachedDrv = _: drv:
    if pkgs.lib.isDerivation drv then
      derivation
        {
          name = "${drv.name}-to-cached";
          system = drv.system;
          builder = "/bin/sh";
          args = [ "-c" "${pkgs.coreutils}/bin/ln -s ${drv} $out" ];
        }
    else
      drv;
in
pkgs.lib.mapAttrs toCachedDrv pkgs.my-packages
```

**Comment by Mic92** [comment]
There is no way to detect that from `nix-build-uncached` except the workaround you posted. Should we just add this to the documentation?

**Comment by zimbatm** [comment]
`nix-build-uncached` could load the target with ^ this script in between. But it gets messy quickly and makes error reporting worse.

Here is another untested version with recurse into attrs support: https://gist.github.com/7bc9210b1c4d0afe390f0d425b50e02f

**Comment by Mic92** [comment]
Indeed. I would rather prefer to document rather than implementing it this method since not everybody has this use case. Those targets would also need to be uploaded to the binary cache.

**Comment by zimbatm** [comment]
(updated the gist with a working version)

The issue is quite likely to happen in monorepo setups where the number of build targets changes often. In my experience, the engineers merge pull requests and don't realize what is happening. A few weeks later people complain that the build is getting slower and slower. At that point, some Nix expert is called in and goes through the same type of debugging that I did. Making the connection with `allowSubstitutes` is not straight-forward and was only possible because I had prior knowledge about it.

Hopefully, at that point they search the repo and find this issue or the documentation.

**Comment by madjar** [comment]
Would it be a reasonable solution for nix-build-uncached to check if the drv file contains `("allowSubstitutes","")`?

The drawback is that this changes the behaviour from nix-build, which always builds its arguments, so this might need to live behind a flag.

Context: I'm using home-manager, and I want all the packages in my setup to be in the cache. But the top-level package is a `allowSubstitutes = false` (it's a call to `buildEnv`), which I don't actually wants to build, because it just pulls everything and symlinks it. What I'm interested in is its closure, which may not be easily accessible as a nix expression.

**Comment by zimbatm** [comment]
It would increase the evaluation time. I don't think that it's possible to get those values without evaluating each attribute individually.

**Comment by Mic92** [comment]
Fixed by https://github.com/Mic92/nix-build-uncached/commit/a0fb6144972e9526e54f38954185b76b7447db11
