### ISSUE TITLE
Cannot import path: invalid

### ISSUE THREAD

**Issue by NorfairKing** [Mic92/nix-build-uncached#20]
At https://github.com/NorfairKing/smos/runs/1044625796?check_suite_focus=true
I'm getting this error:
```
 error: cannot import '/nix/store/ma3b77vjls3qrznwh66ix5ivvybx6003-source', since path '/nix/store/sqfs8j0g7bmkir2jf2l64rvm3xdfng52-source.drv' is not valid, at /nix/store/pswlp0b96blwb7ab07ihdr7ridf3a00l-source/nix/default.nix:26:1
```

While the regular nix build passes.

**Comment by Mic92** [comment]
Can you also try the latest release of `nix-build-uncached` (v1.0.0). You are using an old version.

**Comment by NorfairKing** [comment]
`nix-build-uncached` won't end up being useful for my usecase: https://twitter.com/kerckhove_ts/status/1299642714103971840
So I didn't end up doing this. Thanks for the quick help though!
