### ISSUE TITLE
question about cachix's garbage collection

### ISSUE THREAD

**Issue by bbigras** [Mic92/nix-build-uncached#22]
I'm using `nix-build-uncached` with cachix.

Since `nix-build-uncached` will skip building stuff already in my cachix cache, will cachix's garbage collection remove stuff I need since I didn't build/push them in the last runs?

**Comment by Mic92** [comment]
I would say so because I assume that cachix only account for GET requests and not HEAD requests. cc @domenkozar

**Comment by domenkozar** [comment]
That's a good question! 

Cachix will set last accessed for nar GET request and not narinfo requests.

I might change that to narinfo to cover this use case, I don't see any downsides.

**Comment by bbigras** [comment]
> I might change that to narinfo to cover this use case, I don't see any downsides.

That would be great. Unless I'm wrong it would fix a pretty big downside of using nix-build-uncached.

**Comment by Mic92** [comment]
Ok. There is nothing that nix-build-uncached can really fix here.
