### ISSUE TITLE
Detection for '--experimental-features' has changed?

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-build-uncached#26]
After yesterday's change, I tested locally, but hadn't tested with my CI builder that doesn't have daemon-wide experimental-features enabled.

Checked today, it hit another snag. The daemon doesn't have it enabled, the CLI is `nixUnstable`. But, you detect this and try to accomodate it. It looks like maybe the heuristic needs an update, due to behavior change in the CLI?

```
$ nix build --out-link /run/user/1000/tmp.DJ6KSQ7TNR/result --option extra-binary-caches https://cache.nixos.org https://nixpkgs-wayland.cachix.org --option trusted-public-keys cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= --option build-cores 0 --option narinfo-cache-negative-ttl 0 /nix/store/c9snhq4763cs50w9bapa2k88g9c1ac97-wofi-ac8dc17ab751.drv [snip]
error: --- Error --- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
nix-build-uncached: nix build failed: exit status 1
```

I logged into my CI box, ran `nix-shell` for my project to load up the same env:

```
[nix-shell:~/nixpkgs-wayland]$ nix; echo $?
[prints usage]
0

[nix-shell:~/nixpkgs-wayland]$ nix build nixpkgs.hello
error: --- Error ---------------------------------------------------------------------------------- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
1
```

So I think the detection needs to actually try something more aggressively?

**Comment by Mic92** [comment]
I could invert the check and check if it accepts `--experimental-features`:

```
$ nix --experimental-features nix-command
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
```

**Comment by Mic92** [comment]
Alternative is:

```
nix-instantiate --json --eval --expr 'builtins.nixVersion'
"3.0pre20200829_f156513"
```

**Comment by colemickens** [comment]
somehow it didn't occur to me, until now, that I could just pass it as part of buildArgs...

**Comment by colemickens** [comment]
Actually, I'm not sure that works either. I wonder if something else changed about parsing?

(Look at the very end, looks like it's not finding the end correctly either. Maybe I should just try to author a patch.)

`
$ nix build --out-link /tmp/tmp.e32WWWULn3/result --experimental-features nix-command flakes ca-references --option extra-binary-caches https://cache.nixos.org https://nixpkgs-wayland.cachix.org --option trusted-public-keys cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= --option build-cores 0 --option narinfo-cache-negative-ttl 0 /nix/store/74614ifqkp4yg5sbb0scfa7rm2pkw521-waybar-faacd76f627f4f7ad3413a44870e089fbdb6539e.drv /nix/store/dirqzgii9l7b7pdfldqx5rzj5fc7r30h-freerdp-96bb5696747703788d7fcff6cf4e3bc3c6ad8190.drv /nix/store/igph9rir2bkppyl4bif1gsxp3lm40vd1-wlay-1e316ca92d38856c517af4a0a7d88c8589bd2131.drv /nix/store/v0jmn5r2z4car9qs0yfqhknvm6939ax1-slurp-bfff873301e92364df80ef6aaa4a6b14f76177af.drv /nix/store/02y053w3l931sgpr1qkjn9yx2024lyqw-emacs-pgtk-bef27f591a23fb0da071b79bf78c453c7f220a40.drv /nix/store/s94mqgi951ysgagdaasak7zfilsji7pq-wlroots-8348fc3ef8b992fce097bef81111eda3677957f4.drv /nix/store/6a91wiva16zfh9wi4grp1gs2ava8byhz-wl-gammactl-611846ce8f5f6e7fe1afb100416cceb8af54afb2.drv /nix/store/7byil2k37048vx24rgkjfyah5isp5daq-sway-0df5753aed57c6b5e3a5f64ff410cadf8d96c35c.drv /nix/store/c8bdaw99h5kfv5f4iwk6ygbbq9k1p0j3-gtk-layer-shell-3b3b935b1643eb58e6cf5a9432b4470d568bfbc2.drv /nix/store/88a9cillkn427wy0xkqq0x1d3ds32vax-glpaper-9e7ec7cd270a.drv /nix/store/sna06njd2lmnry1kyv7x5cfm1ycs8zc4-wlrobs-bcc570977627.drv /nix/store/mz2jpwd1wi12vpvmrcdwybfn4dq75c2c-nwg-launchers-44962915eaa68578d6ea8fe28a585a29b837f7b3.drv /nix/store/rzma1kxfaki4ajjs84zr2jznp6a9d8a4-wayfire-3375ded33674c3a9e4e814cb0832d22eb50565ce.drv /nix/store/w7gdnxcacaxwn8spsawqzy3v5kpr2czb-cage-0d85c1652e676806a5c065bdc88e83f0b33a0a5e.drv /nix/store/x82sln5qia0717hb66pr72lw1a5fdhwm-wofi-e3db9b8075e7.drv /nix/store/1c6sq6ywhjlw3mp8iv0sj6zm7szyxkhy-oguri-d6f195acca5de465532cba3efd4b0c592ca542d9.drv /nix/store/bsxgzbqazhqrgnl0z8fp080cq4zw18qr-sway-unwrapped-0df5753aed57c6b5e3a5f64ff410cadf8d96c35c.drv /nix/store/f2adh8cfr1yl8q3sshmrmbflssr1pbl6-lavalauncher-bcf3b785aa41326e1a4818e7f395620291130d44.drv /nix/store/lc4ynfc2xjjav1jcmqv3whpbjs78b0kn-wayvnc-7f5fbbf6135cc0cc320a8e1f247613cdfd2d07e0.drv /nix/store/y7gzfhgffzhhw5pl4icrpa0wbq4g3gks-xdg-desktop-portal-wlr-24bc68f0f2b4bc0e96646f0f8bfa3af2d57c21f1.drv this path will be fetched (0.10 MiB download, 0.58 MiB unpacked): /nix/store/ywdimkf6psva4874wr56idhwcwgfl8qh-sway.drv /nix/store/bznvkj529zc5h24myhnn8iblx3dh5qi3-extra-cmake-modules-5.73.0
`

**Comment by colemickens** [comment]
Update:

1. The detection is broken, and fails to detect for latest nix versions (as per this issue).

2. *When* it *does* detect, it appends to the build args list which overrides any the user might've passed.

3. **Luckily** *if* the detection is broken, the user can pass `--experimental-features "nix-command"` manually to `-build-args`.

I'm wondering if it `nix-build-uncached` should actually be doing any detection at all.

**Comment by Mic92** [comment]
Fixed in https://github.com/Mic92/nix-build-uncached/pull/30
