### ISSUE TITLE
Using nix copy after nix-build-uncached

### ISSUE THREAD

**Issue by jfroche** [Mic92/nix-build-uncached#33]
Hello,

Once we have build all the (uncached) packages defined in our overlays using `nix-build-uncached`,
we copy the packages to a directory using `nix copy`. This command sometimes fails because some package are not in the nix store (as it hasn't been build/fetched by `nix-build-uncached`).
Would it sound ok to add an option in `nix-build-uncached` to fetch the non build packages in the local nix store. We would then end up with the same packages in the /nix/store as if we would have run `nix-build`.

Thank you for this great tool ! All this should be a parameter to `nix-build`.

**Comment by Mic92** [comment]
I don't quite understand your intend here. Do you want to copy all unbuild packages to the nix store again or only a subset of it?

**Comment by jfroche** [comment]
Right, we want to have all unbuild packages to the nix store to be able to copy them elsewhere using nix copy

**Comment by Mic92** [comment]
Ok. So why don't you use `nix-build` instead of `nix-build-uncached`? This should have the effect you are just describing.

**Comment by jfroche** [comment]
The problem is that I thought nix-build would always build the derivation...
Sorry for the losing your time on this one.
