### ISSUE TITLE
Pass flags only to `nix build`

### ISSUE THREAD

**Issue by IvarWithoutBones** [Mic92/nix-build-uncached#40]
Currently, there is (as far as I'm aware) no way to pass flags only to the `nix build`. 

When passing flags through `-build-flags`, these also get appended to the `nix-build`. Due to the syntax of these commands not being the same, it causes some issues for me. I want to access compilation logs, but currently I cannot pass the `-L` flag to `nix build`, as `nix-build` doesn't understand that flag.

**Comment by colemickens** [comment]
I also haven't found a way around this.

**Comment by adisbladis** [comment]
This was actually fixed in d9b091b919c6a7a9afbdf37d37673fde38166525.

@Mic92 I think it's time to tag a new release?

**Comment by Mic92** [comment]
Just released v1.1.1
