### ISSUE TITLE
Do not truncate logs?

### ISSUE THREAD

**Issue by nomeata** [Mic92/nix-build-uncached#42]
Since switching from `nix-build` to `nix-build-uncached`, it seems that build failures are truncated on our CI system to the last 10 lines. I am not sure if this is due to `nix-build-uncached`, or the way `nix-build-uncached` builds stuff. But it would be good to get full logs back. Is there an easy way to achieve that?

**Comment by colemickens** [comment]
see #40

**Comment by nomeata** [comment]
Ah, thanks, I wasn’t sure if there is a flag for that (and `nix build --help` doesn't mention it).

Ah, now that I tired `nix --help` I see `-L` there, so this is really a duplicate of #40.

Is there a strong reason why `nix-build-uncached` uses `nix build` and not `nix-build`?

**Comment by colemickens** [comment]
>Is there a strong reason why nix-build-uncached uses nix build and not nix-build?

it has to do with a bug in `nix build --dry-run` ... not sure if that's still a blocker.

cc: @zimbatm who I sort of remember being involved in the related discussion?

**Comment by colemickens** [comment]
Actually, see here: https://github.com/NixOS/nix/issues/3681

Also, supposedly nix can do some of this in its own but as usual it's not
documented in a meaningful way.

**Comment by nomeata** [comment]
So that nix issue seems to be fixed. What does this mean for the issue at hand?
