### ISSUE TITLE
nix-build-uncached doesn't build anything with nix 2.15

### ISSUE THREAD

**Issue by 999eagle** [Mic92/nix-build-uncached#52]
With the release of Nix 2.15 (see the [release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.15.html)), this PR was merged: NixOS/nix#7600. As `nix-build-uncached` calls `nix build /nix/store/hash-name.drv`, only the derivations will be built but no outputs. With Nix 2.15 the new syntax `nix build '/nix/store/hash-name.drv^*'` must be used to actually build all outputs.

**Comment by domenkozar** [comment]
cc @Mic92

**Comment by Mic92** [comment]
Just noticed that I forgot to push a readme update that deprecated the project... 1a7664d908c5fab6a1996e4269f271fc4fd4188f
I also invited @domenkozar as a contributor in case someone want to fix this issue. @domenkozar feel free to make releases...

**Comment by Mic92** [comment]
If not I will drop this from nixpkgs when I get to it.

**Comment by Artturin** [comment]
https://github.com/Mic92/nix-build-uncached/pull/53

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/227640
