### ISSUE TITLE
error: attribute '' missing

### ISSUE THREAD

**Issue by anmonteiro** [Mic92/nix-build-uncached#6]
Hey!

Was trying to use this in one of my projects, and I end up getting this error:

```
error: attribute '' missing, at /tmp/295224101.nix:6:1
```

Here's a small repro that causes this for me:

```nix
# foo.nix, ran with `nix run nixpkgs.nix-build-uncached -c nix-build-uncached ./foo.nix`
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "some-pkg";
  version = "0.0.1";
  src = ./.;

  dontBuild = true;
  installPhase = ''
    touch $out
  '';
}
```

I managed to get my hands on the generated tmp file which has the following contents:

```nix
{...} @args:
let
  set' = import "/home/anmonteiro/projects/lol/nix/foo.nix";
  set = if builtins.isFunction set' then set' args else set';
in [
set.""
]
```

**Comment by anmonteiro** [comment]
I dug into the code a little, and one possible fix is to not output `set.""` if `attrPath` is `nil` here:

https://github.com/Mic92/nix-build-uncached/blob/f5bf6ccdffb1defbb4d52239f3d2f6ec3fe2ecd2/main.go#L124

**Comment by Mic92** [comment]
Right now we only support attribute sets:

```
with import <nixpkgs> {};

let
  some-pkg = stdenv.mkDerivation {
  name = "some-pkg";
  version = "0.0.1";
  src = ./.;

  dontBuild = true;
  installPhase = ''
    touch $out
  '';
}; in {
  inherit some-pkg;
};
```

**Comment by Mic92** [comment]
The use-case was repository with many packages, your single package get likely rebuild on every pull request, because the source changes every time.

**Comment by anmonteiro** [comment]
Thank you, that context is helpful.

**Comment by Mic92** [comment]
I might improve the error message here but I actually don't want to increase the complexity of my tool just to support building single packages.

**Comment by anmonteiro** [comment]
I agree it makes sense to keep the complexity down where possible. Working around it is also easy.

In any case, thanks for making this. It's gonna prove useful for keeping my overlays tested.

**Comment by Mic92** [comment]
Latest master actually supports a single derivation as well now.
